### ISSUE TITLE
Command line utility

### ISSUE THREAD

**Issue by azaretsky** [mlabs-haskell/hydra-demo#4]
Basic communtication with a Hydra Node via WebSocket API:
* given a set of UTxO's, an ADA amount and a gesture ("rock", "paper", "scissors"), lock that amount to the script from #2, i.e. place a bet
* submit a dummy transaction with the bet datum encoded in TxMetadata
* submit a redeem transaction

**Comment by nazrhom** [comment]
Closed in #18
